//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public int EmployerID { get; set; }
        public string EmployerMail { get; set; }
        public string EmployerPhone { get; set; }
        public string FIO { get; set; }
    }
}
