//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Task12Entities : DbContext
    {
        public Task12Entities()
            : base("name=Task12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employers> Employers { get; set; }
        public virtual DbSet<OrderBoard> OrderBoard { get; set; }
        public virtual DbSet<RoleID> RoleID { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
